// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SquareVerifier = artifacts.require('Verifier');

contract('Verifier', accounts => {

    const account_one = accounts[0];
    let proof = {
        "proof": {
            "a": ["0x06c7baa07954ecc5ec08bb483bcb1cfe28b8221e6e0ceba4dd703b24c34a8f84", "0x2500e7f04974ebc316bc7215a238112a3f710eceb70f63549c1fabd9fc54cf6b"],
            "b": [["0x00d67678819a86896c53adca673aa5d62a1e644ce622f8bdc67c78de25a0033f", "0x16d009fbfbd988b26708ccbdbbc430b5dabe5034bfeaee513cd02cb27ca6433b"], ["0x2aa63f5de1714c003feae8d0b675758487bc8bf0aadd5dd044a07b025aa60de0", "0x2b7d43cab98767892fc53244f7cb42ef4ad1e6a26499e6ad59cb29f590a5eb67"]],
            "c": ["0x2575c84774463f2a03b372836ed43a9c580a39811d6be9d1f4a33f93619bde80", "0x14b7b0918f74d878fb783f5251c6c660bfbfdb305b6b121a1330ccc40bb9e6a2"]
        },
        "correctInputs": ["0x0000000000000000000000000000000000000000000000000000000000000010", "0x0000000000000000000000000000000000000000000000000000000000000001"],
        "inCorrectInputs": ["0x0000000000000000000000000000000000000000000000000000000000001110", "0x0000000000000000000000000000000000000000000000000000000000001111"]
    };

    describe('test square verifier - zokrates', function () {
        beforeEach(async function () {
            this.contract = await SquareVerifier.new({ from: account_one });
        })

        // Test verification with correct proof
        // - use the contents from proof.json generated from zokrates steps
        it('Test verification with correct proof', async function () {
            const { proof: { a, b, c }, correctInputs: inputs } = proof;
            let isCorrect = await this.contract.verifyTx(a, b, c, inputs);

            assert.equal(true, isCorrect, "Invalid proof result");
        })

        // Test verification with incorrect proof
        it('Test verification with incorrect proof', async function () {
            const { proof: { a, b, c }, inCorrectInputs: inputs } = proof;
            let isCorrect = await this.contract.verifyTx(a, b, c, inputs);

            assert.equal(false, isCorrect, "Invalid proof result");
        })

    });
})



